create table if not exists public.sensor_readings (
    id bigint generated by default as identity primary key,
    timestamp timestamptz not null,
    node_id text not null,
    tilt_x double precision,
    tilt_y double precision,
    vibration double precision,
    crack_disp_mm double precision,
    temperature double precision,
    battery double precision,
    state text,
    constraint sensor_readings_node_timestamp_key unique (node_id, timestamp)
);

create index if not exists sensor_readings_timestamp_idx
    on public.sensor_readings (timestamp desc);

create index if not exists sensor_readings_node_timestamp_idx
    on public.sensor_readings (node_id, timestamp);

-- ============================================================
-- AUTHORIZED USERS (Dynamic Email Authorization & Alerts)
-- ============================================================
create table if not exists public.authorized_users (
    id bigint generated by default as identity primary key,
    email text not null unique,
    name text,
    active boolean not null default true,
    created_at timestamptz not null default now()
);

create index if not exists authorized_users_email_idx
    on public.authorized_users (email);

create index if not exists authorized_users_active_idx
    on public.authorized_users (active);

-- Enable Row Level Security (RLS)
alter table public.authorized_users enable row level security;

-- Allow read access to active users for authentication and alerts
create policy "Allow read access to authorized_users"
    on public.authorized_users for select
    using (true);

-- Allow insert/update for management
create policy "Allow management access to authorized_users"
    on public.authorized_users for all
    using (true);
