create table if not exists public.sensor_readings (
    id bigint generated by default as identity primary key,
    timestamp timestamptz not null,
    node_id text not null,
    tilt_x double precision,
    tilt_y double precision,
    vibration double precision,
    crack_disp_mm double precision,
    temperature double precision,
    battery double precision,
    state text,
    constraint sensor_readings_node_timestamp_key unique (node_id, timestamp)
);

create index if not exists sensor_readings_timestamp_idx
    on public.sensor_readings (timestamp desc);

create index if not exists sensor_readings_node_timestamp_idx
    on public.sensor_readings (node_id, timestamp);
